drop table if exists bookmarks;

create table bookmarks(
    id integer primary key generated by default as identity,
    title text not null,
    link text not null,
    body text,
    rating integer not null
);

insert into bookmarks(title,link, body, rating) values ('title1', 'randomlink1', 'randombody', 1),
('title2', 'randomlink2', 'randombody', 2),('title3', 'randomlink3', 'randombody', 3),('title4', 'randomlink4', 'omg its rated a 4', 4),('Favorite Google Site', 'https://www.google.com', 'its just Google', 5),('Youtube', 'https://www.youtube.com', 'Youtube homepage', 3),('MDN', 'https://www.mdn.com', 'Mozilla dev network', 5),('cnn', 'https://www.cnn.com', 'news site', 2),('yahoo', 'https://yahoo.com', 'Dinosaur days', 4),('9gag', 'https://www.9gag.com', 'ifunny ripoff', 3)
